### ISSUE TITLE
Latest meeting does not have a stable URL

### ISSUE THREAD

**Issue by jfischer** [BayPiggies/pelican_website#10]
This is the issue that Bill and I discussed at the last meeting.

LinkedIn would like to have a URL to the latest meeting that will still be valid after the meeting is over. I believe they are using this for an internal webpage.

For example, the February meeting is currently available at http://baypiggies.net, but not at http://baypiggies.net/meeting-2017-02-23.html. Once we put up the page for the March meeting, the Feb meeting is now available at the date-specific URL and not at BayPiggies.net.

I believe this is a side effect of the way we are tricking Pelican into putting the latest meeting on the front page via the :url: property.

Anyway, I can think of three possible solutions:

1. Bill had mentions a way to handle this in the Makefile. I think that would be ideal, if possible.
2. We could maintain two pages: one called latest.rst and one with called Meeting-YYYY-MM-DD.rst. This would need to be tested to verify it has no unintended consequences. It also requires some additional manual work each month (with potential for mistakes).
3. For my personal site, I have a similar problem in that I needed to maintain alias pages for old WordPress URLs (I migrated from WordPress to Pelican). I modified the [pelican-alias](https://github.com/Nitron/pelican-alias) plugin to generate Nginx URL aliases for the nginx site configuration file (the vanilla pelican-alias plugin creates client-side redirects, which don't always seem to work). I can add this solution, if you happen to be using Nginx.

What do you think?

**Comment by bdbaddog** [comment]
This should be solved now.
