### ISSUE TITLE
Current index RSVP button does not work

### ISSUE THREAD

**Issue by glenjarvis** [BayPiggies/pelican_website#3]
When clicking, the following message is displayed:

```
Invalid Authorization request
If you were directed here by another application, contact its developer
```

**Comment by bdbaddog** [comment]
Filed ticket with meetup.com. It worked just a while before you filed the ticket for me.

**Comment by jfischer** [comment]
I tried it last month and it worked fine. There are a few things to be aware of:

- It won't work with the test server, as the API appears to validate that it was coming off the domain name of the website
- There are two places in the "top" html snippet that include the event id. If you miss one of these, I assume it won't work

At some point, this button will stop working -- they apparently have deprecated this API, see issue meetup/api#197
