### ISSUE TITLE
Add GitHub integration for Slack #website when there is a new PR

### ISSUE THREAD

**Issue by glenjarvis** [BayPiggies/pelican_website#51]
In Slack, @bdbaddog  (Bill Deegan) asked this:

https://baypiggies.slack.com/archives/CMWANMSTT/p1568662223007200

```
Bill Deegan 12:30 PM
can we get github to message #website when there’s a PR?
```

Glen volunteered to look at a web hook integration with GitHub to Slack.

**Comment by bdbaddog** [comment]
Done.
